baseURL = 'https://feelinlucky.github.io/blogs/'
locale = 'en-us'
title = '​🇳🇮​​🇨​​🇪​ ​🇹​​🇭​​🇮​​🇳​​🇬​​🇸​'
theme = 'book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true